data:
  train_bs: 2
  train_width: 448
  train_height: 768
  n_sample_frames: 32
  cond_type: 'smplx'

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True
  gradient_checkpointing: True
  max_train_steps: 100000
  max_grad_norm: 1.0
  # lr
  learning_rate: 5e-5
  scale_lr: False
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 1000

unet_additional_kwargs:
  use_inflated_groupnorm: true
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false
  use_motion_module: true
  motion_module_resolutions:
    - 1
    - 2
    - 4
    - 8
  motion_module_mid_block: true
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
      - Temporal_Self
      - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 128
    temporal_attention_dim_div: 1

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
  steps_offset: 1
  clip_sample: false

pretrained_base_model_path: './checkpoints/sd-image-variations-diffusers'
pretrained_vae_path: './checkpoints/sd-vae-ft-mse'

denoising_unet_path: "./outputs/MusePose_stage1-20241116020542/denoising_unet-18000.pth"
reference_unet_path: "./outputs/MusePose_stage1-20241116020542/reference_unet-18000.pth"
pose_guider_path: "./outputs/MusePose_stage1-20241116020542/pose_guider-18000.pth"
motion_module_path: "./outputs/MusePose_stage2-20241116150755/motion_module-8000.pth"

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.05
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True

seed: 1234
checkpointing_steps: 1000
exp_name: 'MusePose_stage2'
output_dir: './outputs'