data:
  train_bs: 8
  train_width: 576
  train_height: 1024
  # Margin of frame indexes between ref and tgt images
  sample_margin: 30

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True
  gradient_checkpointing: False
  max_train_steps: 50000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1.0e-5
  scale_lr: False
  lr_warmup_steps: 100
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: False
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 1000


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
  steps_offset: 1
  clip_sample: false

pretrained_base_model_path: './checkpoints/sd-image-variations-diffusers'
pretrained_vae_path: './checkpoints/sd-vae-ft-mse'

denoising_unet_path: "./outputs/MusePose_stage1-20241021112227/denoising_unet-4000.pth"
reference_unet_path: "./outputs/MusePose_stage1-20241021112227/reference_unet-4000.pth"
pose_guider_path: "./outputs/MusePose_stage1-20241021112227/pose_guider-4000.pth"

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True
pose_guider_pretrain: True

seed: 1234
checkpointing_steps: 1000
exp_name: 'MusePose_stage1'
output_dir: './outputs'